### PR TITLE
Update workflows

### PR DESCRIPTION
**Pull request by Reneedvir**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @Reneedvir,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
@Reneedvir, judging by the fact the call to /service/groupuser/action/add [https://github.com/kaltura/developer-platform/pull/11/files#diff-e8fd2c187aae262737142bb1dade1a94R49] has no parameters block yet, I assume you're not done working on this recipe yet?

**Comment by Reneedvir** [comment]
@jessp01 Done now, but the default in the user add step 1 should be "GROUP" but I coulddnt figure out a way to do that.

**Comment by jessp01** [comment]
@Reneedvir,

I made a few fixes to your original MD, please see the final version here:
https://raw.githubusercontent.com/kaltura/developer-platform/master/workflows/group_management/readme.md

Here is a main list of the fixes, for future ref:
- The values for KalturaUserType::GROUP and KalturaUserType::USER are integers, therefore, it should be:
```
"consoleDefault": 0
"consoleDefault": 1
```
and not:
```
"consoleDefault": "0"
"consoleDefault": "1"
```

- The workflow should include two calls for /service/user/action/add, first one creates a USER, the other a GROUP

-   /service/groupuser/action/add requires two parameters: groupUser[userId], groupUser[groupId]

The workflow now works as expected but in order for it to show under https://developer.kaltura.com/workflows, https://github.com/kaltura/developer-platform/blob/master/ovp.LucyBot.yml#L305 needs to be edited.
I can do it for you but I need:
- The title you wish to use [I assume it's Group Management but would rather be sure]
- An icon https://github.com/kaltura/developer-platform/blob/master/assets/img/icons/
For example, the icon for the "upload" recipe is:
https://github.com/kaltura/developer-platform/blob/master/assets/img/icons/upload.png

Thanks,

**Comment by Reneedvir** [comment]
Thanks Jess!
Title is Group management
Icon: should this be from within existing icons? who creates a new one? Or should this recipe be within one of the existing workflow sections? I think a person icon makes most sense or the same one as engage.

**Pull request merged**
