### PR TITLE
Fixed swift

### PR DESCRIPTION
**Pull request by tan-tan-kanarek**

### CODE REVIEW

**Comment by zoharbabin** [comment]
@jessp01 and @bobby-brennan - please review and merge if OK.

**Comment by jessp01** [comment]
Looks fine to me. Merging and will generate a new version. Will let you know when you can review again.

**Comment by jessp01** [comment]
@tan-tan-kanarek - following your pull, I've made the changes in the right place:
https://github.com/kaltura/developer-platform/commit/32ff352836ed821bba93a3cb6e9ec0243dc8da9b

[test/golden is only for CI purposes, really].

You can see the changes here: https://developer.kaltura.com:8443

Please confirm.

**Comment by tan-tan-kanarek** [comment]
Looks good.

**Comment by jessp01** [comment]
Thanks @tan-tan-kanarek - so, just to confirm, can we consider https://github.com/kaltura/developer-platform/issues/46 as done?

**Comment by tan-tan-kanarek** [comment]
Yes

**Comment by jessp01** [comment]
Thanks, @tan-tan-kanarek. @bobby-brennan - please see my comment here:
https://github.com/kaltura/developer-platform/issues/46#issuecomment-392582454

We can close the issue once that's fixed.

**Pull request merged**
